### ISSUE TITLE
请教大佬

### ISSUE THREAD

**Issue by GD2021** [yxnwh/checkin#1]
我想单拉kjwj.js，
拉了 ql raw kjwj.js，运行不了，缺依赖好像，请问这个需要什么依赖？我单独装一下。

**Comment by yxnwh** [comment]
请先阅读下readme
另外如果运行脚本时缺少某个依赖，请到青龙面板对应脚本的日志下，查看缺少的依赖名，然后到依赖管理里面安装一下
